### ISSUE TITLE
ability to pass an entire object to a component

### ISSUE THREAD

**Issue by kylemac** [reshape/preact-components#1]
would be good to be able to do 

```html
<my-component state='stateObj' />
```
instead of individually like

```html
<my-component state-title="foo" state-description="bar" />
```

**Comment by jescalan** [comment]
It definitely would, but this is an html parsing issue. Basically, if there is a double quote in your object, html parsers will treat it as the end of the attribute value, and everything will get messed up. And unfortunately, it's really difficult to ensure that there are no double quotes anywhere inside your object, especially when consuming content from a CMS.

One solution it to encode to base64 and decode on the other end -- it's possible we could build in some shortcut functions for this that could be pulled from this library. This is the way that we handle the initial state hydration, and it seems to work ok. Any thoughts on this?

**Comment by kylemac** [comment]
closed by https://github.com/reshape/preact-ssr/commit/33a000c6e97fe833338cc8ffe09fbf51fe6de2f8
